language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
dist: focal # ou "bionic" pour Ubuntu 18.04

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="core.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
