language: python
python:
  - "3.10"
dist: focal

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

script:
  - python manage.py test
