language: python
python:
  - 3.10

services:
  - postgresql

addons:
  postgresql: "13"

env:
  - DJANGO_SETTINGS_MODULE="settings.travis"

before_script:
  - psql -c 'create database test_db;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
