# Generated by Django 4.0.6 on 2022-07-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_category_options_category_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['user'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='name',
        ),
        migrations.AddField(
            model_name='favorite',
            name='prod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='blog.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='sub',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='blog.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
